### PR TITLE
Versioning gulp commands added. 

### PR DESCRIPTION
**Pull request by JeremiahReichardt**
gulp build --version and gulp build-version STRING-OR-NUMBER-HERE

### CODE REVIEW

**Comment by normmcgarry** [comment]
I support this, but I'm concerned about the bloating of the build.js gulp task with versioning. Do we think this is a good spot for this, or is there a simple way to break it out into a version.js gulp task? I'm not sure... @draeton?

**Comment by JeremiahReichardt** [comment]
I wasn't sure either - is this a feature of Build or its own task as Version? It is super easy to break it back out into its own task. @draeton thoughts feelings?

**Comment by draeton** [comment]
I think it should be a separate task, for clarity

**Comment by JeremiahReichardt** [comment]
Version is now split out into its own task and two issues have been fixed. This new task is not included within Build task - I think it would be best placed inside another task that calls Build, Version, and then deploys.

**Pull request merged**
